<?php
/**
 * @var \M2E\TikTokShop\Block\Adminhtml\Category\Chooser\Prepare $block
 */
?>

<script>
    require([
        'TikTokShop/Category/Chooser'
    ], () => {
        window.TikTokShopCategoryChooserObj = new TikTokShopCategoryChooser(
            <?= /* @noEscape */ $block->getShopId() ?>,
            <?= /* @noEscape */ $block->getAccountId() ?>
        );
    });
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "category_search": {
                        "component": "M2E_TikTokShop/js/Category/Chooser/Tabs/Search",
                        "searchUrl": "<?= /* @noEscape */ $block->getSearchUrl() ?>",
                        "shopId": <?= /* @noEscape */ $block->getShopId() ?>
                    }
                }
            }
        }
    }
</script>
