<?php

// @codingStandardsIgnoreFile

/** @var \M2E\TikTokShop\Block\Adminhtml\ControlPanel\Inspection\VersionInfo $block */
?>

<table class="form-list">

    <tr>
        <td class="label">
            <label><?= __('Latest Version'); ?>: </label>
        </td>
        <td class="value">
            <?php if ($this->latestPublicVersion) : ?>
                <?= $this->latestPublicVersion; ?>
                <?php $versionForUrl = str_replace('.', '-', $this->latestPublicVersion); ?>
                <a href="<?= "https://docs-m2.m2epro.com/m2e-tiktok-shop-release-notes-policy"; ?>" target="_blank">
                    <?= __('[release notes]'); ?>
                </a>
            <?php else : ?>
                --
            <?php endif; ?>
        </td>
    </tr>

    <?php if (!$block->getData('is_support_mode')) : ?>
        <tr>
            <td class="label">
                <label><?= __('History'); ?>: </label>
            </td>
            <td class="value">
                <?php
                $url = $block->getUrl(
                    '*/controlPanel_database/manageTable',
                    ['table' => \M2E\TikTokShop\Helper\Module\Database\Tables::TABLE_NAME_SETUP]
                ); ?>
                <a target="_blank" href="<?= $url; ?>"><?= __('show'); ?></a>
            </td>
        </tr>
    <?php endif; ?>
</table>
