<?php
/**
 * @var \M2E\TikTokShop\Block\Adminhtml\ManufacturerConfiguration\Edit\Form\ComplianceResponsiblePerson\FormElementRender $this
 * @var \M2E\TikTokShop\Block\Adminhtml\ManufacturerConfiguration\Edit\Form\ComplianceResponsiblePerson\FormElement $element
 */

$element = $this->getElement();

?>

<?php foreach ($element->getSavedResponsiblePersons() as $index => $value) : ?>
    <div class="admin__field field field-responsible_person_id with-addon required _required">
        <label class="label admin__field-label" for="responsible_person_id_<?= /* @noEscape */ $index ?>"">
            <span><?= /* @noEscape */ __('Responsible Person') ?></span>
        </label>
        <div class="admin__field-control control">
            <?= /* @noEscape */ $element->renderAttributesDropdown($index) ?>
            <span class="actions" <?= empty($value) ? 'style="display:none"' : '' ?>>
                <?= /* @noEscape */ $element->createButtonsBlock(
                    [
                        $element->renderResponsiblePersonLinksHtml(true, $index),
                        $element->renderResponsiblePersonLinksHtml(false, $index),
                        $element->renderRefreshButtonHtml($index),
                        $element->renderRemoveRowButton($index),
                    ]
                ) ?>
            </span>
        </div>
    </div>
<?php endforeach; ?>

<div class="admin__field add_row_wrapper field with-addon" <?= empty($element->getAccountId()) ? 'style="display:none"' : '' ?>>
    <label class="label admin__field-label"></label>
    <div class="admin__field-control control">
        <?= /* @noEscape */ $element->renderAddRowButton() ?>
    </div>
</div>

