<?php

declare(strict_types=1);

namespace M2E\TikTokShop\Model\Order\ReturnRequest;

class Status
{
    public const RETURN_OR_REFUND_REQUEST_PENDING = 'RETURN_OR_REFUND_REQUEST_PENDING';
    public const REFUND_OR_RETURN_REQUEST_REJECT = 'REFUND_OR_RETURN_REQUEST_REJECT';
    public const BUYER_AWAITING_BUYER_SHIP = 'AWAITING_BUYER_SHIP';
    public const BUYER_SHIPPED_ITEM = 'BUYER_SHIPPED_ITEM';
    public const RETURN_OR_REFUND_REQUEST_CANCEL = 'RETURN_OR_REFUND_REQUEST_CANCEL';
    public const RETURN_OR_REFUND_REQUEST_COMPLETE = 'RETURN_OR_REFUND_REQUEST_COMPLETE';
}
