<?php

// @codingStandardsIgnoreFile

/** @var \M2E\TikTokShop\Block\Adminhtml\Template\SellingFormat\PriceChange $block */

$type = $block->getPriceType();
$typeForDataset = str_replace('_', '-', $type);
$priceModifierData = $block->getPriceModifier();

$attributes = $block->getAllAttributes();
$priceModifierAttributes = $block->getPriceModifierAttributes($priceModifierData);
$attributesByInputTypes = $block->getAttributesByInputTypes();

?>

<div id="<?= /* @noEscape */ $type ?>_change_container"></div>
<div id="<?= /* @noEscape */ $type ?>_calculation_example" class="price_change_row" style="display: none;"></div>
<button title="<?php
/* @noEscape */ echo $block->__('Add Price Change'); ?>"
        id="<?= /* @noEscape */ $type ?>_change_add_row_button"
        type="button"
        class="action-default scalable action primary price_change_remove price_change_additional_element">
    <span><?php
      /* @noEscape */ echo $block->__('Add Price Change'); ?></span>
</button>

<div id="<?= /* @noEscape */ $type ?>_change_row_template" style="display: none;">
    <div style="position: relative;" class="price_change_row">
        <select id="<?= /* @noEscape */ $type ?>_modifier_mode_%index%"
                name="<?= /* @noEscape */ $type ?>_modifier_mode[%index%]"
                class="select admin__control-select TikTokShop-validate-price-modifier price_modifier_mode required-entry"
                data-<?= /* @noEscape */ $typeForDataset ?>-change-index="%index%"
                style="width: 250px;">
            <option
                value="<?php
                echo \M2E\TikTokShop\Model\Template\SellingFormat::PRICE_MODIFIER_ABSOLUTE_INCREASE; ?>">
                <?php
              /* @noEscape */ echo $block->__('Absolute Value increase'); ?></option>
            <option
                value="<?php
                echo \M2E\TikTokShop\Model\Template\SellingFormat::PRICE_MODIFIER_ABSOLUTE_DECREASE; ?>">
                <?php
              /* @noEscape */ echo $block->__('Absolute Value decrease'); ?></option>
            <option
                value="<?php
                echo \M2E\TikTokShop\Model\Template\SellingFormat::PRICE_MODIFIER_PERCENTAGE_INCREASE; ?>">
                <?php
              /* @noEscape */ echo $block->__('Percentage increase'); ?></option>
            <option
                value="<?php
                echo \M2E\TikTokShop\Model\Template\SellingFormat::PRICE_MODIFIER_PERCENTAGE_DECREASE; ?>">
                <?php
              /* @noEscape */ echo $block->__('Percentage decrease'); ?></option>

            <optgroup class="TikTokShop-custom-attribute-optgroup"
                      label="Magento Attribute">
                <?php
                foreach ($priceModifierAttributes as $attributeCode): ?>
                    <?php
                    if (!$block->magentoAttributeHelper->isExistInAttributesArray($attributeCode, $attributes)): ?>
                        <option attribute_code="<?php
                      /* @noEscape */ echo $attributeCode; ?>"
                                value="<?php
                                echo \M2E\TikTokShop\Model\Template\SellingFormat::PRICE_MODIFIER_ATTRIBUTE; ?>">
                            <?php
                            echo $block->escapeHtml(
                                $block->magentoAttributeHelper->getAttributeLabel($attributeCode)
                            ); ?>
                        </option>
                    <?php
                    endif; ?>
                <?php
                endforeach; ?>

                <?php
                foreach ($attributesByInputTypes['text_price'] as $attribute) : ?>
                    <option attribute_code="<?php
                  /* @noEscape */ echo $attribute['code']; ?>"
                            value="<?php
                            echo \M2E\TikTokShop\Model\Template\SellingFormat::PRICE_MODIFIER_ATTRIBUTE; ?>">
                        <?php
                        echo $block->escapeHtml($attribute['label']); ?>
                    </option>
                <?php
                endforeach; ?>
            </optgroup>
        </select>

        <input name="<?= /* @noEscape */ $type ?>_modifier_value[%index%]"
               id="<?= /* @noEscape */ $type ?>_modifier_value_%index%"
               type="text"
               class="admin__control-text input-text coef price_change_additional_element"/>

        <input type="hidden"
               name="<?= /* @noEscape */ $type ?>_modifier_attribute[%index%]"
               id="<?= /* @noEscape */ $type ?>_modifier_attribute_%index%"/>

        <button title="<?php
      /* @noEscape */ echo $block->__('Remove'); ?>"
                id="<?= /* @noEscape */ $type ?>_modifier_row_remove_button_%index%"
                type="button"
                class="action-default scalable action primary price_change_remove price_change_additional_element">
            <span><?php
              /* @noEscape */ echo $block->__('Remove'); ?></span>
        </button>
    </div>
</div>
