<?php

// @codingStandardsIgnoreFile

/** @var \M2E\TikTokShop\Block\Adminhtml\Wizard\InstallationTikTokShop\Installation\ListingTutorial\Content $block */

?>

<div class="wizard_block">
    <h2>
        <?= /* @noEscape */ __('Congratulations! You have registered your M2E TikTok Shop Connect Extension and linked ' .
            'your TikTok Shop Account to it.'); ?>
    </h2>

    <p>
        <?= /* @noEscape */ __('The next step involves creating your first M2E TikTok Shop Connect Listing.'); ?>
    </p>
    <br/>

    <p>
        <?= /* @noEscape */ __('M2E TikTok Shop Connect Listing is a group of Magento Products combined under specific sets ' .
            'of rules. <br/>These are the Products which will be offered as TikTok Shop Items by a Seller on ' .
            'a particular Shop.'); ?>
    </p>
    <br/>

    <p>
        <?= /* @noEscape */ __('Click on the <strong>Create First Listing</strong> button to proceed. Or click on ' .
            'the <strong>Skip</strong> button if you want to create your first listing later.'); ?>
    </p>
</div>
