<?php
/** @var \M2E\TikTokShop\Block\Adminhtml\Category\Attributes\Validation\Popup $block */
?>

<script>
    require([
        'TikTokShop/Category/Attribute/Validation/Popup'
    ], function(Popup) {
        window.TikTokShopCategoryAttributeValidationPopup = new Popup(
            {
                modalOpenUrl: '<?= $block->escapeHtml($block->getModalOpenUrl()) ?>',
            },
        );
    });
</script>


