<?php

// @codingStandardsIgnoreFile

/**
 * @var \M2E\TikTokShop\Block\Adminhtml\ControlPanel\Info\Actual $block
 */

?>

<table class="form-list">

    <tr>
        <td class="label">
            <label><?= __('System | Current Time'); ?>: </label>
        </td>
        <td class="value">
            <?= "$block->systemName | $block->systemTime"; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Magento'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->magentoInfo ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Module [Public]'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->publicVersion ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Module [Setup]'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->setupVersion ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Module Environment'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->moduleEnvironment ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Maintenance'); ?>: </label>
        </td>
        <td class="value">
            <table class="form-list">
                <tr>
                    <td>
                        <span style="<?= $block->maintenanceMode ? 'color: green;' :
                            'color: red;'; ?>"><?= $block->maintenanceMode ? __('enabled') : __('disabled'); ?></span>
                    </td>
                    <td>
                        <span style="color: orange;">
                            &nbsp;<a href="<?= $block->getUrl('*/controlPanel_inspection/changeMaintenanceMode') ?>"
                                     onclick="return confirm('Are you sure?');">[<?= __('change'); ?>]</a>
                        </span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Core Resource'); ?>: </label>
        </td>
        <td class="value">
            <table class="form-list">
                <tr>
                    <td>
                        <span <?php
                        if ($block->setupVersion != $block->coreResourceVersion || $block->setupVersion != $block->coreResourceDataVersion) : echo ' style="color: red;" '; endif; ?>>
                            <?= ($block->coreResourceVersion ?: 'N/A')
                            . ' / ' . ($block->coreResourceDataVersion ?: 'N/A') ?>
                        </span>
                    </td>
                    <td>
                        <span style="color: orange;">
                            &nbsp;<a href="javascript:void(0);"
                                     onclick="return setupManagementActionHandler.askAdditionalParametersForAction('Repeat upgrade from the following version:', '<?= $block->getUrl(
                                         '*/controlPanel_inspection/setMagentoCoreSetupValue',
                                         ['_query' => ['version' => '#version#']]
                                     ) ?>', 'version');">[<?= __('set'); ?>]</a>
                        </span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('PHP'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->phpVersion ?>
            <a target="_blank" href="<?= $block->getUrl('*/controlPanel_inspection/phpInfo') ?>"
               style="padding-left: 10px;"><?= __('[info]') ?></a>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Server API'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->phpApi ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Memory Limit'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->memoryLimit . ' Mb' ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('Max Execution Time'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->maxExecutionTime == 0 ? __('Unlimited') : $block->maxExecutionTime . ' sec'; ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('MySQL'); ?>: </label>
        </td>
        <td class="value">
            <?= $block->mySqlVersion ?>
        </td>
    </tr>

    <tr>
        <td class="label">
            <label><?= __('MySQL Database | Tables Prefix'); ?>: </label>
        </td>
        <td class="value">
            <?= "$this->mySqlDatabaseName | $this->mySqlPrefix"; ?>
        </td>
    </tr>
</table>
