<?php

/** @var \M2E\TikTokShop\Block\Adminhtml\TikTokShop\Order\View\CancellationRequest $block */

?>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
        <strong class="admin__collapsible-title">
            <span><?= /* @noEscape */ __('Buyer Cancellation Request') ?></span>
        </strong>
    </div>
    <table class="order-info form-list">
        <tr>
            <td class="label"><?= /* @noEscape */ __('Cancellation Reason') ?></td>
            <td><p><?= /* @noEscape */ $block->getBuyerCancellationRequestReason() ?></p></td>
        </tr>
        <tr>
            <td class="label"><?= /* @noEscape */ __('Action') ?></td>
            <td>
                <button class="primary buyer-cancellation-accept"><?= /* @noEscape */ __('Accept') ?></button>
                <button class="primary buyer-cancellation-decline"><?= /* @noEscape */ __('Decline') ?></button>
            </td>
        </tr>
    </table>
</div>
