<?php

// @codingStandardsIgnoreFile

/** @var \M2E\TikTokShop\Block\Adminhtml\TikTokShop\Template\Description\Preview $block */

?>

<?php
echo $block->getLayout()->createBlock(\M2E\TikTokShop\Block\Adminhtml\HelpBlock::class)->setData([
    'style' => 'margin-top: 30px',
    'no_hide' => true,
    'title' => $block->__('Description Preview'),
    'content' => $block->__(
        'If your description contains M2E TikTok Shop Connect Attributes, some of them such as Image URLs, Images, etc. might display for the previewing the value which is different from the actual one that will be sent to TikTok Shop.'
    ),
])->toHtml() ?>

<div class="pagination_container page-main-actions">
    <div class="product_title">
        <h2><?php
          /* @noEscape */ echo $block->getData('title'); ?> (ID: <?php
          /* @noEscape */ echo $block->getData('magento_product_id'); ?>)</h2>
    </div>
</div>

<div class="description_container">
    <?php
  /* @noEscape */ echo $block->getData('description'); ?>
</div>
