<?php

// @codingStandardsIgnoreFile

/**
 * @var M2E\TikTokShop\Block\Adminhtml\Order\Item\Product\Options\Mapping $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>

<style>

    .popup-window .magento_message {
        padding: 0;
    }

    .buttons-container {
        padding: 10px;
        text-align: right;
    }

</style>

<div id="product_options_mapping_content" class="hor-scroll" style="">

    <?= /* @noEscape */ $block->getChildHtml('product_mapping_options_help_block'); ?>

    <input
        type="hidden" name="order_item_ids" class="form-element"
        value="<?= $escaper->escapeHtmlAttr($block->getOrderItemsIdsAsString()) ?>"/>

    <h4><?= /* @noEscape */ __('Channel Options') ?></h4>

    <div style="border-bottom: 1px solid #E7E7E7; padding: 5px 5px;">

        <?php
        if (empty($block->getData('channel_options'))) : ?>
            <span style="font-style: italic;">
                <?= /* @noEscape */ __('No Channel Options are available.'); ?>
            </span>
        <?php
        else: ?>
            <dl>

                <?php
                foreach ($block->getData('channel_options') as $channelOption) : ?>
                    <dt>
                        <label>
                        <span style="font-weight: bold; font-style: italic;">
                            <?php
                            echo \M2E\Core\Helper\Data::escapeHtml($channelOption['label']); ?>:
                        </span>
                            <span>
                            &nbsp;<?php
                                echo \M2E\Core\Helper\Data::escapeHtml($channelOption['value']); ?>
                        </span>
                        </label>
                    </dt>
                <?php
                endforeach; ?>

            </dl>

        <?php
        endif; ?>

    </div>

    <br/>

    <h4><?php
        echo \M2E\Core\Helper\Data::escapeHtml($block->getProductTypeHeader()) ?></h4>

    <div>

        <dl>

            <?php
            foreach ($block->getData('magento_options') as $option) : ?>
                <dt>
                    <label>
                        <span style="color: #eb5202">*</span>&nbsp;<?php
                        echo \M2E\Core\Helper\Data::escapeHtml($option['label']); ?>
                    </label>
                </dt>
                <dd style="border-bottom: 1px solid #E7E7E7; margin: 5px 0 15px; padding: 0 0 12px;">
                    <div class="input-box">
                        <select name="option_id[<?php
                        echo (int)$option['option_id']; ?>]"
                                class="form-element select admin__control-select required-entry">
                            <option value="" class="empty"><?php
                              /* @noEscape */ echo $block->__('Select Option...'); ?></option>
                            <?php
                            foreach ($option['values'] as $value) : ?>
                                <?php
                                $optionValue = json_encode([
                                    'value_id' => $value['value_id'],
                                    'product_ids' => $value['product_ids'],
                                ]);
                                $optionLabel = $value['label'];

                                $selected = $block->isMagentoOptionSelected($option, $value);
                                ?>
                                <option value="<?php
                                echo \M2E\Core\Helper\Data::escapeHtml($optionValue); ?>" <?php
                                        if ($selected) :
                                        ?>selected="selected"<?php
                                endif; ?>>
                                    <?php
                                    echo \M2E\Core\Helper\Data::escapeHtml($optionLabel); ?>
                                </option>
                            <?php
                            endforeach; ?>
                        </select>
                    </div>
                </dd>
            <?php
            endforeach; ?>

        </dl>

    </div>

    <div id="selected_product_option_is_out_of_stock" style="display: none;">
        <?php
        echo $block->getChildHtml('product_mapping_options_out_of_stock_message'); ?>
    </div>
</div>
