<?php

// @codingStandardsIgnoreFile

/**
 * @var M2E\TikTokShop\Block\Adminhtml\Order\Item\Product\Options\Mapping $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>

<style>

    .popup-window .magento_message {
        padding: 0;
    }

    .buttons-container {
        padding: 10px;
        text-align: right;
    }

</style>

<div id="product_options_mapping_content" class="hor-scroll" style="">

    <?= /* @noEscape */ $block->getChildHtml('product_mapping_options_help_block'); ?>

    <input
        type="hidden" name="order_item_ids" class="form-element"
        value="<?= $escaper->escapeHtmlAttr($block->getOrderItemsIdsAsString()) ?>"/>

    <h4><?= /* @noEscape */ __('Channel Options') ?></h4>

    <div style="border-bottom: 1px solid #E7E7E7; padding: 5px 5px;">

        <?php
        if (empty($block->getChanelOption())) : ?>
            <span style="font-style: italic;">
                <?= /* @noEscape */ __('No Channel Options are available.'); ?>
            </span>
        <?php
        else: ?>
            <dl>

                <?php
                foreach ($block->getChanelOption() as $channelOption) : ?>
                    <dt>
                        <label>
                        <span style="font-style: italic;">
                            <?= \M2E\Core\Helper\Data::escapeHtml($channelOption['label']); ?>
                        </span>
                        </label>
                    </dt>
                <?php
                endforeach; ?>

            </dl>

        <?php
        endif; ?>

    </div>

    <br/>

    <h4><?php
        echo \M2E\Core\Helper\Data::escapeHtml($block->getProductTypeHeader()) ?></h4>

    <div>

        <dl>
            <?php foreach ($block->getMagentoOptions() as $option) : ?>
                <?= /* @noEscape */ $block->renderOptionElement($option) ?>
            <?php endforeach; ?>
        </dl>

    </div>

    <div id="selected_product_option_is_out_of_stock" style="display: none;">
        <?php
        echo $block->getChildHtml('product_mapping_options_out_of_stock_message'); ?>
    </div>
</div>
