<?php

// @codingStandardsIgnoreFile

/** @var \M2E\TikTokShop\Block\Adminhtml\TikTokShop\Template\Synchronization\Edit\Form\Data $block */

?>

<div class="page-layout-admin-2columns-left" style="margin-top: 20px;">
    <div class="page-columns">
        <div class="main-col">
            <div id="tabs_edit_form_data">
            </div>
        </div>
        <div class="side-col">
            <?php
            echo $block->getChildHtml('tabs'); ?>
        </div>
    </div>
</div>
